import type { Metadata } from "next";
import { yekan } from "@/utils/fonts";
import "./globals.css";
import Layout from "@/layout/Layaout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa" dir="rtl">
            <body className={yekan.className}>
                <Layout>{children}</Layout>
            </body>
        </html>
    );
}
